/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConexaoBD;
import controller.DAOPaciente;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import model.BeansPacientes;
import model.ModeloTabela;

/**
 *
 * @author Matheus
 */
public class FormPaciente extends javax.swing.JFrame {

    ConexaoBD conex = new ConexaoBD();
    BeansPacientes pac = new BeansPacientes();
    DAOPaciente dao = new DAOPaciente();
    int flag = 0;
    int resposta = 0;

    public FormPaciente() {
        initComponents();

        preencherBairros();

        try {
            preencherTabela("SELECT paci_codigo, paci_nome, paci_telefone, paci_rg, bainome FROM pacientes INNER JOIN bairro ON paci_codigo = baicodigo ORDER BY paci_nome");
        } catch (SQLException ex) {
            Logger.getLogger(FormPaciente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldNome = new javax.swing.JTextField();
        jFormattedTextFieldRG = new javax.swing.JFormattedTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldRua = new javax.swing.JTextField();
        jFormattedTextFieldCep = new javax.swing.JFormattedTextField();
        jTextFieldComplemento = new javax.swing.JTextField();
        jComboBoxBairros = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTablePaciente = new javax.swing.JTable();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jButtonAlterar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldPesquisa = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jFormattedTextFieldDTnasc = new javax.swing.JFormattedTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextFieldCodPac = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Nome:");

        jLabel3.setText("Nascimento:");

        jLabel4.setText("RG:");

        jLabel5.setText("Telefone:");

        jTextFieldNome.setEnabled(false);
        jTextFieldNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldNomeActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldRG.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#######-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldRG.setEnabled(false);

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) #####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setText("Rua:");

        jLabel8.setText("CEP:");

        jLabel9.setText("Complemento");

        jLabel10.setText("Bairro:");

        jTextFieldRua.setEnabled(false);

        try {
            jFormattedTextFieldCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldCep.setEnabled(false);

        jTextFieldComplemento.setEnabled(false);

        jComboBoxBairros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxBairros.setEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldComplemento)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jLabel10)
                        .addGap(18, 18, 18)
                        .addComponent(jComboBoxBairros, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jTextFieldRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldComplemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxBairros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jLabel6.setText("Endereço");

        jTablePaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jTablePaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablePacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablePaciente);

        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonAlterar.setText("Alterar");
        jButtonAlterar.setEnabled(false);
        jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlterarActionPerformed(evt);
            }
        });

        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.setRolloverEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jLabel11.setText("Pesquisa:");

        jButtonBuscar.setText("Buscar");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        try {
            jFormattedTextFieldDTnasc.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldDTnasc.setEnabled(false);

        jLabel12.setText("Cod:");

        jTextFieldCodPac.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(15, 15, 15)
                                .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel12))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, 291, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextFieldCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE)
                            .addComponent(jFormattedTextFieldDTnasc)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 37, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonBuscar))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 597, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22)))
                .addGap(18, 18, 18))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextFieldCodPac, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFormattedTextFieldDTnasc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldRG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)))
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar))
                .addGap(22, 22, 22)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAlterar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Formulário de Pacientes");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(216, 216, 216))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(707, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void preencherBairros() {
        conex.conexao();

        conex.executaSql("SELECT * FROM bairro ORDER BY bainome");

        try {
            conex.rs.first();
            jComboBoxBairros.removeAllItems();

            do {
                jComboBoxBairros.addItem(conex.rs.getString("bainome"));
            } while (conex.rs.next());

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao preencher bairros" + ex);
        }
    }


    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;

        jTextFieldComplemento.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jFormattedTextFieldDTnasc.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jComboBoxBairros.setEnabled(true);

        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);

    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jTextFieldNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldNomeActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed

        if (jTextFieldNome.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o NOME");
            jTextFieldNome.requestFocus();
        } else if (jFormattedTextFieldDTnasc.getText().equals("  /  /    ")) {
            JOptionPane.showMessageDialog(null, "Preencha a data de nascimento para continuar");
            jFormattedTextFieldDTnasc.requestFocus();
        } else if (jFormattedTextFieldRG.getText().equals("       - ")) {
            JOptionPane.showMessageDialog(null, "Preencha o RG para continuar");
            jFormattedTextFieldRG.requestFocus();
        } else if (jFormattedTextFieldTelefone.getText().equals("(  )     -    ")) {
            JOptionPane.showMessageDialog(null, "Preencha o TELEFONE para continuar");
            jFormattedTextFieldTelefone.requestFocus();
        } else if (jTextFieldRua.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha a RUA para continuar");
            jTextFieldRua.requestFocus();
        } else if (jFormattedTextFieldCep.getText().equals("     -   ")) {
            JOptionPane.showMessageDialog(null, "Preencha o CEP para continuar");
            jFormattedTextFieldCep.requestFocus();
        } else if (jTextFieldComplemento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Preencha o COMPLEMENTO continuar");
            jTextFieldComplemento.requestFocus();
        } else if (flag == 1) {

            pac.setNomePac(jTextFieldNome.getText());
            pac.setCep(jFormattedTextFieldCep.getText());
            pac.setComplemento(jTextFieldComplemento.getText());
            pac.setNasc(jFormattedTextFieldDTnasc.getText());
            pac.setRg(jFormattedTextFieldRG.getText());
            pac.setNomeBairro((String) jComboBoxBairros.getSelectedItem());
            pac.setTelefone(jFormattedTextFieldTelefone.getText());
            pac.setRua(jTextFieldRua.getText());
            dao.Salvar(pac);

            try {
                preencherTabela("SELECT paci_codigo, paci_nome, paci_telefone, paci_rg, bainome FROM pacientes INNER JOIN bairro ON paci_codigo = baicodigo ORDER BY paci_nome");
            } catch (SQLException ex) {
                Logger.getLogger(FormPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }

            jTextFieldComplemento.setEnabled(!true);
            jTextFieldNome.setEnabled(!true);
            jTextFieldRua.setEnabled(!true);
            jFormattedTextFieldCep.setEnabled(!true);
            jFormattedTextFieldDTnasc.setEnabled(!true);
            jFormattedTextFieldRG.setEnabled(!true);
            jFormattedTextFieldTelefone.setEnabled(!true);
            jComboBoxBairros.setEnabled(!true);

            jButtonCancelar.setEnabled(!true);
            jButtonSalvar.setEnabled(!true);
            jButtonNovo.setEnabled(!false);
            jButtonAlterar.setEnabled(false);
            jButtonExcluir.setEnabled(false);

            jTextFieldCodPac.setText("");
            jTextFieldComplemento.setText("");
            jTextFieldNome.setText("");
            jTextFieldRua.setText("");
            jFormattedTextFieldCep.setText("");
            jFormattedTextFieldDTnasc.setText("");
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldTelefone.setText("");

        } else {
            pac.setNomePac(jTextFieldNome.getText());
            pac.setCep(jFormattedTextFieldCep.getText());
            pac.setComplemento(jTextFieldComplemento.getText());
            pac.setNasc(jFormattedTextFieldDTnasc.getText());
            pac.setRg(jFormattedTextFieldRG.getText());
            pac.setNomeBairro((String) jComboBoxBairros.getSelectedItem());
            pac.setTelefone(jFormattedTextFieldTelefone.getText());
            pac.setRua(jTextFieldRua.getText());
            pac.setCodPac(Integer.parseInt(jTextFieldCodPac.getText()));
            dao.Alterar(pac);

            try {
                preencherTabela("SELECT paci_codigo, paci_nome, paci_telefone, paci_rg, bainome FROM pacientes INNER JOIN bairro ON paci_codigo = baicodigo ORDER BY paci_nome");
            } catch (SQLException ex) {
                Logger.getLogger(FormPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }

            jTextFieldComplemento.setEnabled(!true);
            jTextFieldNome.setEnabled(!true);
            jTextFieldRua.setEnabled(!true);
            jFormattedTextFieldCep.setEnabled(!true);
            jFormattedTextFieldDTnasc.setEnabled(!true);
            jFormattedTextFieldRG.setEnabled(!true);
            jFormattedTextFieldTelefone.setEnabled(!true);
            jComboBoxBairros.setEnabled(!true);

            jButtonCancelar.setEnabled(!true);
            jButtonSalvar.setEnabled(!true);
            jButtonNovo.setEnabled(!false);
            jButtonAlterar.setEnabled(false);
            jButtonExcluir.setEnabled(false);

            jTextFieldCodPac.setText("");
            jTextFieldComplemento.setText("");
            jTextFieldNome.setText("");
            jTextFieldRua.setText("");
            jFormattedTextFieldCep.setText("");
            jFormattedTextFieldDTnasc.setText("");
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldTelefone.setText("");
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
        flag = 2;
        jTextFieldComplemento.setEnabled(true);
        jTextFieldNome.setEnabled(true);
        jTextFieldRua.setEnabled(true);
        jFormattedTextFieldCep.setEnabled(true);
        jFormattedTextFieldDTnasc.setEnabled(true);
        jFormattedTextFieldRG.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jComboBoxBairros.setEnabled(true);

        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
    }//GEN-LAST:event_jButtonAlterarActionPerformed

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
        jTextFieldComplemento.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFieldCep.setEnabled(!true);
        jFormattedTextFieldDTnasc.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldTelefone.setEnabled(!true);
        jComboBoxBairros.setEnabled(!true);

        jButtonCancelar.setEnabled(true);
        jButtonSalvar.setEnabled(!true);
        jButtonNovo.setEnabled(false);
        jButtonAlterar.setEnabled(!false);
        jButtonExcluir.setEnabled(!false);

        pac.setPesquisa(jTextFieldPesquisa.getText());
        BeansPacientes pac1 = dao.buscaPaciente(pac);
        jTextFieldNome.setText(pac1.getNomePac());
        jTextFieldCodPac.setText(String.valueOf(pac1.getCodPac()));
        jFormattedTextFieldDTnasc.setText(pac1.getNasc());
        jFormattedTextFieldRG.setText(pac1.getRg());
        jFormattedTextFieldTelefone.setText(pac1.getTelefone());
        jTextFieldRua.setText(pac1.getRua());
        jFormattedTextFieldCep.setText(pac1.getCep());
        jTextFieldComplemento.setText(pac1.getComplemento());
        jComboBoxBairros.setSelectedItem(pac1.getNomeBairro());
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
        resposta = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente excluir?");

        if (resposta == JOptionPane.YES_OPTION) {

            pac.setCodPac(Integer.parseInt(jTextFieldCodPac.getText()));
            dao.Excluir(pac);

            try {
                preencherTabela("SELECT paci_codigo, paci_nome, paci_telefone, paci_rg, bainome FROM pacientes INNER JOIN bairro ON paci_codigo = baicodigo ORDER BY paci_nome");
            } catch (SQLException ex) {
                Logger.getLogger(FormPaciente.class.getName()).log(Level.SEVERE, null, ex);
            }

            jTextFieldCodPac.setText("");
            jTextFieldComplemento.setText("");
            jTextFieldNome.setText("");
            jTextFieldRua.setText("");
            jFormattedTextFieldCep.setText("");
            jFormattedTextFieldDTnasc.setText("");
            jFormattedTextFieldRG.setText("");
            jFormattedTextFieldTelefone.setText("");

            jTextFieldComplemento.setEnabled(!true);
            jTextFieldNome.setEnabled(!true);
            jTextFieldRua.setEnabled(!true);
            jFormattedTextFieldCep.setEnabled(!true);
            jFormattedTextFieldDTnasc.setEnabled(!true);
            jFormattedTextFieldRG.setEnabled(!true);
            jFormattedTextFieldTelefone.setEnabled(!true);
            jComboBoxBairros.setEnabled(!true);

            jButtonCancelar.setEnabled(true);
            jButtonSalvar.setEnabled(true);
            jButtonNovo.setEnabled(false);
            jButtonAlterar.setEnabled(!false);
            jButtonExcluir.setEnabled(!false);
        }


    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jTablePacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablePacienteMouseClicked

        String nome_paciente = "" + jTablePaciente.getValueAt(jTablePaciente.getSelectedRow(), 1);
        conex.conexao();
        conex.executaSql("SELECT * FROM pacientes WHERE paci_nome ='" + nome_paciente + "'");
        try {
            conex.rs.first();
            jTextFieldCodPac.setText(String.valueOf(conex.rs.getInt("paci_codigo")));
            jTextFieldNome.setText(conex.rs.getString("paci_nome"));
            jFormattedTextFieldDTnasc.setText(conex.rs.getString("paci_nasc"));
            jFormattedTextFieldRG.setText(conex.rs.getString("paci_rg"));
            jFormattedTextFieldTelefone.setText(conex.rs.getString("paci_telefone"));
            jTextFieldRua.setText(conex.rs.getString("paci_rua"));
            jTextFieldComplemento.setText(conex.rs.getString("paci_complemento"));
            jFormattedTextFieldCep.setText(conex.rs.getString("paci_cep"));
            ConexaoBD conexPesquisa = new ConexaoBD();
            conexPesquisa.conexao();
            conexPesquisa.executaSql("SELECT * FROM bairro where baicodigo =" + conex.rs.getInt("paci_baicodigo"));
            conexPesquisa.rs.first();

            jComboBoxBairros.setSelectedItem(conexPesquisa.rs.getString("bainome"));
            conexPesquisa.desconecta();

            jTextFieldComplemento.setEnabled(!true);
            jTextFieldNome.setEnabled(!true);
            jTextFieldRua.setEnabled(!true);
            jFormattedTextFieldCep.setEnabled(!true);
            jFormattedTextFieldDTnasc.setEnabled(!true);
            jFormattedTextFieldRG.setEnabled(!true);
            jFormattedTextFieldTelefone.setEnabled(!true);
            jComboBoxBairros.setEnabled(!true);

            jButtonCancelar.setEnabled(true);
            jButtonSalvar.setEnabled(!true);
            jButtonNovo.setEnabled(false);
            jButtonAlterar.setEnabled(!false);
            jButtonExcluir.setEnabled(!false);

        } catch (SQLException ex) {
            Logger.getLogger(FormMedico.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "Erro ao selecionar dados" + ex);
        }
    }//GEN-LAST:event_jTablePacienteMouseClicked

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
        jTextFieldCodPac.setText("");
        jTextFieldComplemento.setText("");
        jTextFieldNome.setText("");
        jTextFieldRua.setText("");
        jFormattedTextFieldCep.setText("");
        jFormattedTextFieldDTnasc.setText("");
        jFormattedTextFieldRG.setText("");
        jFormattedTextFieldTelefone.setText("");

        jTextFieldComplemento.setEnabled(!true);
        jTextFieldNome.setEnabled(!true);
        jTextFieldRua.setEnabled(!true);
        jFormattedTextFieldCep.setEnabled(!true);
        jFormattedTextFieldDTnasc.setEnabled(!true);
        jFormattedTextFieldRG.setEnabled(!true);
        jFormattedTextFieldTelefone.setEnabled(!true);
        jComboBoxBairros.setEnabled(!true);

        jButtonCancelar.setEnabled(!true);
        jButtonSalvar.setEnabled(!true);
        jButtonNovo.setEnabled(!false);
        jButtonAlterar.setEnabled(false);
        jButtonExcluir.setEnabled(false);


    }//GEN-LAST:event_jButtonCancelarActionPerformed

    public void preencherTabela(String sql) throws SQLException {
        ArrayList dados = new ArrayList();
        String[] colunas = new String[]{"ID", "Nome", "Telefone", "RG", "Bairro"};

        conex.conexao();
        conex.executaSql(sql);

        try {
            conex.rs.first();
            do {
                dados.add(new Object[]{conex.rs.getInt("paci_codigo"), conex.rs.getString("paci_nome"),
                    conex.rs.getString("paci_telefone"), conex.rs.getString("paci_rg"), conex.rs.getString("bainome")});

            } while (conex.rs.next());
        } catch (SQLException ex) {
            //   JOptionPane.showMessageDialog(rootPane, "Busque por outro médico para preencher a tabela");
        }
        ModeloTabela modelo = new ModeloTabela(dados, colunas);

        jTablePaciente.setModel(modelo);
        jTablePaciente.getColumnModel().getColumn(0).setPreferredWidth(45);
        jTablePaciente.getColumnModel().getColumn(0).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(1).setPreferredWidth(220);
        jTablePaciente.getColumnModel().getColumn(1).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(2).setPreferredWidth(100);
        jTablePaciente.getColumnModel().getColumn(2).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTablePaciente.getColumnModel().getColumn(3).setResizable(false);
        jTablePaciente.getColumnModel().getColumn(4).setPreferredWidth(126);
        jTablePaciente.getColumnModel().getColumn(4).setResizable(false);

        jTablePaciente.getTableHeader().setReorderingAllowed(false);
        jTablePaciente.setAutoResizeMode(jTablePaciente.AUTO_RESIZE_OFF);

        jTablePaciente.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);

        conex.desconecta();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormPaciente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormPaciente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlterar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxBairros;
    private javax.swing.JFormattedTextField jFormattedTextFieldCep;
    private javax.swing.JFormattedTextField jFormattedTextFieldDTnasc;
    private javax.swing.JFormattedTextField jFormattedTextFieldRG;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablePaciente;
    private javax.swing.JTextField jTextFieldCodPac;
    private javax.swing.JTextField jTextFieldComplemento;
    private javax.swing.JTextField jTextFieldNome;
    private javax.swing.JTextField jTextFieldPesquisa;
    private javax.swing.JTextField jTextFieldRua;
    // End of variables declaration//GEN-END:variables
}
