/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.ConexaoBD;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Matheus
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBD conecta = new ConexaoBD();
    FormMedico tela = new FormMedico();
    FormUsuario telaUsu = new FormUsuario();
    FormPaciente telaPac = new FormPaciente();
    FormAgendamento telaAgen = new FormAgendamento();
    
    public TelaPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conecta.conexao();
        
    }
    
    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInternal = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButtonCadMedico = new javax.swing.JButton();
        jButtonCadEnfermeiras = new javax.swing.JButton();
        jButtonCadPacientes = new javax.swing.JButton();
        jButtonAgenda = new javax.swing.JButton();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonFecharBenVindo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelTipoUsuario = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuCadastro = new javax.swing.JMenu();
        jMenuItemCadMedico = new javax.swing.JMenuItem();
        jMenuItemCadPaciente = new javax.swing.JMenuItem();
        jMenuItemCadEnfermeira = new javax.swing.JMenuItem();
        jMenuItemCadUsuarios = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuFerramentas = new javax.swing.JMenu();
        jMenuItemTelaBenvindo = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();
        jMenuItemSair = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem - Vindo");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInternal.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInternal.setLayout(null);

        jLabel2.setText("Cadastros");
        jPanelInternal.add(jLabel2);
        jLabel2.setBounds(10, 10, 80, 14);

        jLabel3.setText("Agenda");
        jPanelInternal.add(jLabel3);
        jLabel3.setBounds(10, 170, 50, 14);

        jButtonCadMedico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/CadMedicos.png"))); // NOI18N
        jButtonCadMedico.setMnemonic('c');
        jButtonCadMedico.setToolTipText("Médicos");
        jButtonCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadMedicoActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadMedico);
        jButtonCadMedico.setBounds(10, 30, 100, 110);

        jButtonCadEnfermeiras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icon-infermeira.png"))); // NOI18N
        jButtonCadEnfermeiras.setToolTipText("Enfermeiras");
        jButtonCadEnfermeiras.setPreferredSize(new java.awt.Dimension(157, 53));
        jPanelInternal.add(jButtonCadEnfermeiras);
        jButtonCadEnfermeiras.setBounds(140, 30, 100, 110);

        jButtonCadPacientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cadPacientes.png"))); // NOI18N
        jButtonCadPacientes.setToolTipText("Pacientes");
        jButtonCadPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadPacientesActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonCadPacientes);
        jButtonCadPacientes.setBounds(270, 30, 100, 110);

        jButtonAgenda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Agenda.png"))); // NOI18N
        jButtonAgenda.setToolTipText("Agendamento");
        jButtonAgenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgendaActionPerformed(evt);
            }
        });
        jPanelInternal.add(jButtonAgenda);
        jButtonAgenda.setBounds(10, 200, 120, 110);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/internalframe.png"))); // NOI18N
        jPanelInternal.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(10, -60, 970, 400);

        jInternalFrameBemVindo.getContentPane().add(jPanelInternal);
        jPanelInternal.setBounds(0, 60, 970, 380);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Sistema de Gerenciamento de:");
        jInternalFrameBemVindo.getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 20, 240, 22);

        jButtonFecharBenVindo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jButtonFecharBenVindo.setToolTipText("Fechar");
        jButtonFecharBenVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharBenVindoActionPerformed(evt);
            }
        });
        jInternalFrameBemVindo.getContentPane().add(jButtonFecharBenVindo);
        jButtonFecharBenVindo.setBounds(870, 0, 100, 60);

        jLabel4.setText("Colaborador(a) :");
        jInternalFrameBemVindo.getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 440, 90, 14);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelUsuario.setText("jLabel5");
        jInternalFrameBemVindo.getContentPane().add(jLabelUsuario);
        jLabelUsuario.setBounds(130, 450, 140, 20);

        jLabel5.setText("Suporte:");
        jInternalFrameBemVindo.getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 440, 70, 14);

        jLabelTipoUsuario.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelTipoUsuario.setText("matheushsouto@gmail.com");
        jInternalFrameBemVindo.getContentPane().add(jLabelTipoUsuario);
        jLabelTipoUsuario.setBounds(410, 450, 230, 22);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(10, 30, 1020, 570);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/fundo_telaprincipal.jpg"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 0, 980, 530);

        jMenuCadastro.setText("Cadastros");

        jMenuItemCadMedico.setText("Médicos");
        jMenuItemCadMedico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadMedicoActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadMedico);

        jMenuItemCadPaciente.setText("Clientes");
        jMenuItemCadPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadPacienteActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadPaciente);

        jMenuItemCadEnfermeira.setText("Enfermeiras");
        jMenuItemCadEnfermeira.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadEnfermeiraActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadEnfermeira);

        jMenuItemCadUsuarios.setText("Usuarios");
        jMenuItemCadUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadUsuariosActionPerformed(evt);
            }
        });
        jMenuCadastro.add(jMenuItemCadUsuarios);

        jMenuBar1.add(jMenuCadastro);

        jMenu2.setText("Relatórios");
        jMenuBar1.add(jMenu2);

        jMenuFerramentas.setText("Ferramentas");

        jMenuItemTelaBenvindo.setText("Tela Bem-Vindo");
        jMenuItemTelaBenvindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTelaBenvindoActionPerformed(evt);
            }
        });
        jMenuFerramentas.add(jMenuItemTelaBenvindo);

        jMenuBar1.add(jMenuFerramentas);

        jMenu1.setText("Agenda");

        jMenuItem1.setText("Agenda Hoje");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setText("Agenda Medico");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuBar1.add(jMenu1);

        jMenuSair.setText("Sair");

        jMenuItemSair.setText("Sair");
        jMenuItemSair.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItemSairMouseClicked(evt);
            }
        });
        jMenuItemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSairActionPerformed(evt);
            }
        });
        jMenuSair.add(jMenuItemSair);

        jMenuBar1.add(jMenuSair);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(995, 595));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemCadPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadPacienteActionPerformed
        try {
            conecta.executaSql("SELECT * FROM usuarios WHERE usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("Administrador")) {
                if (telaPac == null) {
                    telaPac = new FormPaciente();
                    telaPac.setVisible(true);
                    telaPac.setResizable(false);
                } else {
                    telaPac.setVisible(true);
                    telaPac.setResizable(false);
                }
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema" + ex);
            
        }
    }//GEN-LAST:event_jMenuItemCadPacienteActionPerformed

    private void jMenuItemCadEnfermeiraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadEnfermeiraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemCadEnfermeiraActionPerformed

    private void jMenuItemCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadMedicoActionPerformed
        
        try {
            conecta.executaSql("SELECT * FROM usuarios WHERE usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("Administrador")) {
                if (tela == null) {
                    tela = new FormMedico();
                    tela.setVisible(true);
                    tela.setResizable(false);
                } else {
                    tela.setVisible(true);
                    tela.setResizable(false);
                }

//                FormMedico tela = new FormMedico();
                tela.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema" + ex);
            
        }

    }//GEN-LAST:event_jMenuItemCadMedicoActionPerformed

    private void jMenuItemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSairActionPerformed
        //Fechar aplicacao com o Banco de Dados

        TelaLogin tela = new TelaLogin();
        tela.setVisible(true);
        dispose();
        
        conecta.desconecta();
        // Fechar a aplicação

    }//GEN-LAST:event_jMenuItemSairActionPerformed

    private void jMenuItemTelaBenvindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTelaBenvindoActionPerformed
        // Chamando tela de Bem Vindo

        jInternalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemTelaBenvindoActionPerformed

    private void jButtonFecharBenVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharBenVindoActionPerformed
        //Fechar Tela Bem Vindo
        jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharBenVindoActionPerformed

    private void jButtonCadMedicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadMedicoActionPerformed
        // Chamando Formulario de Médico
        try {
            conecta.executaSql("SELECT * FROM usuarios WHERE usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("Administrador")) {
                if (tela == null) {
                    tela = new FormMedico();
                    tela.setVisible(true);
                    tela.setResizable(false);
                } else {
                    tela.setVisible(true);
                    tela.setResizable(false);
                }
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema" + ex);
            
        }
    }//GEN-LAST:event_jButtonCadMedicoActionPerformed

    private void jMenuItemSairMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItemSairMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenuItemSairMouseClicked

    private void jMenuItemCadUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadUsuariosActionPerformed
        try {
            conecta.executaSql("SELECT * FROM usuarios WHERE usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("Administrador")) {
                
                if (telaUsu == null) {
                    telaUsu = new FormUsuario();
                    telaUsu.setVisible(true);
                    telaUsu.setResizable(false);
                } else {
                    telaUsu.setVisible(true);
                    telaUsu.setResizable(false);
                }
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema" + ex);
            
        }
    }//GEN-LAST:event_jMenuItemCadUsuariosActionPerformed

    private void jButtonCadPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadPacientesActionPerformed
        try {
            conecta.executaSql("SELECT * FROM usuarios WHERE usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("Administrador")) {
                if (telaPac == null) {
                    telaPac = new FormPaciente();
                    telaPac.setVisible(true);
                    telaPac.setResizable(false);
                } else {
                    telaPac.setVisible(true);
                    telaPac.setResizable(false);
                }
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema" + ex);
            
        }
        
    }//GEN-LAST:event_jButtonCadPacientesActionPerformed

    private void jButtonAgendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgendaActionPerformed
        try {
            conecta.executaSql("SELECT * FROM usuarios WHERE usu_nome='" + jLabelUsuario.getText() + "'");
            conecta.rs.first();
            if (conecta.rs.getString("usu_tipo").equals("Administrador")) {
                
                if (telaAgen == null) {
                    telaAgen = new FormAgendamento();
                    telaAgen.setVisible(true);
                    telaAgen.setResizable(false);
                } else {
                    telaAgen.setVisible(true);
                    telaAgen.setResizable(false);
                }
                
            } else {
                JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema");
            }
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Você não tem permissao para esta funcionalidade! \n Contate o Administrador do sistema" + ex);
            
        }
    }//GEN-LAST:event_jButtonAgendaActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        FormAgenda tela = new FormAgenda();
        tela.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
     FormAgendaMedico tela = new FormAgendaMedico();
     tela.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAgenda;
    private javax.swing.JButton jButtonCadEnfermeiras;
    private javax.swing.JButton jButtonCadMedico;
    private javax.swing.JButton jButtonCadPacientes;
    private javax.swing.JButton jButtonFecharBenVindo;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelTipoUsuario;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCadastro;
    private javax.swing.JMenu jMenuFerramentas;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItemCadEnfermeira;
    private javax.swing.JMenuItem jMenuItemCadMedico;
    private javax.swing.JMenuItem jMenuItemCadPaciente;
    private javax.swing.JMenuItem jMenuItemCadUsuarios;
    private javax.swing.JMenuItem jMenuItemSair;
    private javax.swing.JMenuItem jMenuItemTelaBenvindo;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JPanel jPanelInternal;
    // End of variables declaration//GEN-END:variables
}
